# Generated by Django 6.0.3 on 2026-04-21 12:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpinteros', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carpintero',
            name='budget_range',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Presupuesto base'),
        ),
        migrations.AddField(
            model_name='carpintero',
            name='rating_avg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Calificación promedio'),
        ),
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('issuer', models.CharField(blank=True, max_length=100, verbose_name='Emisor')),
                ('issued_date', models.DateField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('verified', models.BooleanField(default=False, verbose_name='Verificada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('carpenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificaciones', to='carpinteros.carpintero')),
            ],
            options={
                'verbose_name': 'Certificación',
                'verbose_name_plural': 'Certificaciones',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('carpenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='carpinteros.carpintero')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-created_at'],
            },
        ),
    ]
