# Generated by Django 6.0.3 on 2026-04-21 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carpinteros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del proyecto')),
                ('description', models.TextField(verbose_name='Descripción del proyecto')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Presupuesto')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Fecha límite')),
                ('dimensions', models.CharField(blank=True, max_length=255, verbose_name='Dimensiones')),
                ('materials', models.CharField(blank=True, max_length=255, verbose_name='Materiales preferidos')),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='solicitudes/', verbose_name='Imagen de referencia')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('completed', 'Completada')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('carpenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to='carpinteros.carpintero')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de proyecto',
                'verbose_name_plural': 'Solicitudes de proyectos',
                'ordering': ['-created_at'],
            },
        ),
    ]
