# Generated by Django 6.0.5 on 2026-05-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudproyecto',
            name='project_type',
            field=models.CharField(choices=[('custom', 'Encargo Personalizado'), ('purchase', 'Compra Directa')], default='custom', max_length=20, verbose_name='Tipo de proyecto'),
        ),
    ]
