# Generated by Django 6.0.5 on 2026-05-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_solicitudproyecto_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudproyecto',
            name='status',
            field=models.CharField(choices=[('pending', 'Nueva Solicitud'), ('budgeting', 'Cotizando'), ('accepted', 'Materiales / Inicio'), ('in_progress', 'En Taller'), ('finishing', 'Acabados'), ('ready', 'Listo para Entrega'), ('completed', 'Entregado'), ('rejected', 'Rechazada')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
