# Generated by Django 6.0.5 on 2026-05-22 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_solicitudproyecto_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Total')),
                ('estimated_days', models.PositiveIntegerField(verbose_name='Días estimados de entrega')),
                ('blueprint_file', models.FileField(blank=True, null=True, upload_to='planos/', verbose_name='Plano o Boceto')),
                ('details', models.TextField(verbose_name='Detalles y Especificaciones')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Aceptada por el cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion', to='proyectos.solicitudproyecto')),
            ],
            options={
                'verbose_name': 'Cotización Oficial',
                'verbose_name_plural': 'Cotizaciones Oficiales',
            },
        ),
        migrations.CreateModel(
            name='EstadoFabricacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Nueva Solicitud'), ('budgeting', 'Cotizando'), ('accepted', 'Materiales / Inicio'), ('in_progress', 'En Taller'), ('finishing', 'Acabados'), ('ready', 'Listo para Entrega'), ('completed', 'Entregado'), ('rejected', 'Rechazada')], max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tracking/', verbose_name='Foto de avance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualización')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_fabricacion', to='proyectos.solicitudproyecto')),
            ],
            options={
                'verbose_name': 'Estado de Fabricación',
                'verbose_name_plural': 'Estados de Fabricación',
                'ordering': ['created_at'],
            },
        ),
    ]
