# Generated by Django 6.0.5 on 2026-05-26 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpinteros', '0002_initial'),
        ('proyectos', '0004_cotizacionoficial_estadofabricacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudproyecto',
            name='portafolio_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_directas', to='carpinteros.portafolio'),
        ),
    ]
