# Generated by Django 6.0.5 on 2026-06-01 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_solicitudproyecto_contact_info_and_more'),
        ('proyectos', '0005_solicitudproyecto_portafolio_item'),
    ]

    operations = [
    ]
