# Generated by Django 6.0.5 on 2026-06-01 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_merge_20260531_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadofabricacion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Estado de fabricación', 'verbose_name_plural': 'Estados de fabricación'},
        ),
        migrations.RemoveField(
            model_name='solicitudproyecto',
            name='portafolio_item',
        ),
        migrations.RemoveField(
            model_name='solicitudproyecto',
            name='project_type',
        ),
        migrations.AlterField(
            model_name='estadofabricacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='estadofabricacion',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='fabricacion/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='estadofabricacion',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabricacion', to='proyectos.solicitudproyecto'),
        ),
        migrations.AlterField(
            model_name='estadofabricacion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('completed', 'Completada')], max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='solicitudproyecto',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('completed', 'Completada')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.DeleteModel(
            name='CotizacionOficial',
        ),
    ]
