# Generated by Django 6.0.3 on 2026-04-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carpintero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialties', models.CharField(blank=True, max_length=255, verbose_name='Especialidades')),
                ('experience_years', models.IntegerField(default=0, verbose_name='Años de experiencia')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='URL Portafolio')),
                ('hoja_vida', models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='Hoja de vida')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('approved', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha aprobación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Carpintero',
                'verbose_name_plural': 'Carpinteros',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('rating', models.IntegerField(default=5, verbose_name='Calificación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='portafolio/', verbose_name='Imagen')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Proyecto de portafolio',
                'verbose_name_plural': 'Portafolios',
            },
        ),
    ]
