# Generated by Django 6.0.3 on 2026-04-21 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carpinteros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carpintero',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carpinteros_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carpintero',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_carpintero', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentario',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portafolio',
            name='carpenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portafolio', to='carpinteros.carpintero'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='carpinteros.portafolio'),
        ),
    ]
