# Generated by Django 6.0.4 on 2026-04-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpinteros', '0003_carpintero_budget_range_carpintero_rating_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpintero',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Motivo de rechazo'),
        ),
        migrations.AddField(
            model_name='carpintero',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
