# Generated by Django 6.0.3 on 2026-04-21 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carpinteros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('viewed', 'Visualizó perfil'), ('contacted', 'Contactó'), ('saved', 'Guardó perfil')], max_length=20, verbose_name='Acción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('carpenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='carpinteros.carpintero')),
            ],
            options={
                'verbose_name': 'Interacción',
                'verbose_name_plural': 'Interacciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
