# Generated by Django 5.0.4 on 2026-05-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100, verbose_name='Tipo de acción')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Registro de actividad',
                'verbose_name_plural': 'Registros de actividad',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FailedLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_attempted', models.CharField(blank=True, max_length=100, verbose_name='Email intentado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('fail_reason', models.CharField(blank=True, max_length=100, verbose_name='Motivo del fallo')),
                ('attempt_time', models.DateTimeField(auto_now_add=True, verbose_name='Hora del intento')),
            ],
            options={
                'verbose_name': 'Login fallido',
                'verbose_name_plural': 'Logins fallidos',
                'ordering': ['-attempt_time'],
            },
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('viewed', 'Visualizó perfil'), ('contacted', 'Contactó'), ('saved', 'Guardó perfil')], max_length=20, verbose_name='Acción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Interacción',
                'verbose_name_plural': 'Interacciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Traceability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100, verbose_name='Tipo de acción')),
                ('affected_table', models.CharField(blank=True, max_length=50, verbose_name='Tabla afectada')),
                ('affected_id', models.IntegerField(blank=True, null=True, verbose_name='ID afectado')),
                ('old_value', models.TextField(blank=True, verbose_name='Valor anterior')),
                ('new_value', models.TextField(blank=True, verbose_name='Valor nuevo')),
                ('authority_level', models.CharField(choices=[('user', 'Usuario'), ('carpenter', 'Carpintero'), ('admin', 'Administrador')], default='user', max_length=20, verbose_name='Nivel de autoridad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Trazabilidad',
                'verbose_name_plural': 'Trazabilidad',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior_type', models.CharField(choices=[('view_profile', 'Ver perfil'), ('view_portfolio', 'Ver portafolio'), ('send_request', 'Enviar solicitud'), ('leave_review', 'Dejar reseña'), ('search', 'Búsqueda'), ('filter', 'Filtro'), ('click_whatsapp', 'Click WhatsApp'), ('visit_certified', 'Visitar certificado')], max_length=30, verbose_name='Tipo de comportamiento')),
                ('target_type', models.CharField(choices=[('carpenter', 'Carpintero'), ('portfolio', 'Portafolio'), ('request', 'Solicitud'), ('review', 'Reseña'), ('search', 'Búsqueda')], max_length=20, verbose_name='Tipo objetivo')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='ID objetivo')),
                ('action_data', models.JSONField(blank=True, null=True, verbose_name='Datos de acción')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='Duración (s)')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Comportamiento de usuario',
                'verbose_name_plural': 'Comportamientos de usuario',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_materials', models.CharField(blank=True, max_length=255, verbose_name='Materiales preferidos')),
                ('preferred_styles', models.CharField(blank=True, max_length=255, verbose_name='Estilos preferidos')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Notificaciones habilitadas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Preferencia de usuario',
                'verbose_name_plural': 'Preferencias de usuario',
            },
        ),
    ]
