# Generated by Django 6.0.3 on 2026-04-21 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudproyecto',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, verbose_name='Información de contacto'),
        ),
        migrations.AddField(
            model_name='solicitudproyecto',
            name='response_message',
            field=models.TextField(blank=True, verbose_name='Mensaje de respuesta'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del material')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Unidad')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='proyectos.solicitudproyecto')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
    ]
